Repository hyperledger-cacti/cacti, pull requests merged in 2020-12, with the labels that each got.

#338 chore: release automation
  .gitignore
  lerna.json
  package-lock.json
  package.json
Labels: Developer_Experience, dependencies

#401 fix(tools/docker/besu): all in one image RPC API CLI args
  tools/docker/besu-all-in-one/supervisord.conf
Labels: Besu, bug, dependencies

#412 fix(cockpit): add missing process shim into polyfills
  packages/cactus-cockpit/package.json
  packages/cactus-cockpit/src/polyfills.ts
Labels: bug, dependencies

#420 ci(github): migrate to Github Actions for CI
  .github/workflows/ci.yml
  .travis.yml
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
  packages/cactus-test-tooling/src/test/typescript/integration/fabric/fabric-test-ledger-v1/constructor-validates-options.ts
Labels: dependencies

#382 feat(plugin registry): get keychain by keychain id
  packages/cactus-core-api/src/main/typescript/plugin/plugin-registry.ts
  packages/cactus-core-api/src/test/typescript/unit/plugin-registry.test.ts
Labels: Nice-to-Have

#394 feat(fabric): add run transaction endpoint
  packages/cactus-plugin-ledger-connector-fabric/package-lock.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/json/generated/openapi-spec.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-bin-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-source/deploy-contract-go-source-endpoint-constants.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-source/deploy-contract-go-source-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/i-fabric-signing-identity.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/openapi-spec.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/public-api.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/run-transaction/run-transaction-endpoint-constants.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/run-transaction/run-transaction-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts
  packages/cactus-test-tooling/package-lock.json
  packages/cactus-test-tooling/package.json
  packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
  packages/cactus-test-tooling/src/main/typescript/fabric/i-fabric-signing-identity.ts
  packages/cactus-test-tooling/src/test/typescript/integration/fabric/fabric-test-ledger-v1/constructor-validates-options.ts
  webpack.dev.node.js
  webpack.prod.node.js
Labels: Fabric, enhancement

#404 build(webpack): no bundle generation by default
  examples/cactus-example-supply-chain-backend/package.json
  examples/cactus-example-supply-chain-business-logic-plugin/package.json
  package.json
  packages/cactus-api-client/package.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-common/package.json
  packages/cactus-core-api/package.json
  packages/cactus-core/package.json
  packages/cactus-plugin-consortium-manual/package.json
  packages/cactus-plugin-keychain-memory/package.json
  packages/cactus-plugin-kv-storage-memory/package.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-quorum/package.json
  packages/cactus-plugin-validator-besu/package.json
  packages/cactus-test-api-client/package.json
  packages/cactus-test-cmd-api-server/package.json
  packages/cactus-test-plugin-consortium-manual/package.json
  packages/cactus-test-plugin-ledger-connector-quorum/package.json
  packages/cactus-test-plugin-validator-besu/package.json
  packages/cactus-test-tooling/package.json
Labels: Developer_Experience, Performance

#407 refactor(besu-validator): move code to connector plugin
  packages/cactus-plugin-ledger-connector-besu/src/main/json/generated/openapi-spec.json
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/openapi-spec.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/public-api.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/sign-transaction-endpoint-constants.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/sign-transaction-endpoint-v1.ts
  packages/cactus-plugin-validator-besu/.gitignore
  packages/cactus-plugin-validator-besu/cactus-openapi-spec-plugin-validator-besu.json
  packages/cactus-plugin-validator-besu/package-lock.json
  packages/cactus-plugin-validator-besu/package.json
  packages/cactus-plugin-validator-besu/src/main/typescript/generated/openapi/typescript-axios/.gitignore
  packages/cactus-plugin-validator-besu/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator-ignore
  packages/cactus-plugin-validator-besu/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/FILES
  packages/cactus-plugin-validator-besu/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-validator-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-validator-besu/src/main/typescript/generated/openapi/typescript-axios/base.ts
  packages/cactus-plugin-validator-besu/src/main/typescript/generated/openapi/typescript-axios/configuration.ts
  packages/cactus-plugin-validator-besu/src/main/typescript/generated/openapi/typescript-axios/git_push.sh
  packages/cactus-plugin-validator-besu/src/main/typescript/generated/openapi/typescript-axios/index.ts
  packages/cactus-plugin-validator-besu/src/main/typescript/index.web.ts
  packages/cactus-plugin-validator-besu/src/main/typescript/openapi-spec.ts
  packages/cactus-plugin-validator-besu/src/main/typescript/plugin-validator-besu.ts
  packages/cactus-plugin-validator-besu/src/main/typescript/public-api.ts
  packages/cactus-plugin-validator-besu/tsconfig.json
  packages/cactus-test-plugin-ledger-connector-besu/package-lock.json
  packages/cactus-test-plugin-ledger-connector-besu/package.json
  packages/cactus-test-plugin-ledger-connector-besu/src/main/typescript/index.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/main/typescript/index.web.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/main/typescript/public-api.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/api-surface.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/sign-transaction-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/tsconfig.json
  packages/cactus-test-plugin-validator-besu/src/main/typescript/index.ts
  packages/cactus-test-plugin-validator-besu/src/test/typescript/integration/api-surface.ts
  packages/cactus-test-plugin-validator-besu/src/test/typescript/integration/plugin-validator-besu/sign-transaction-endpoint.test.ts
Labels: Besu

#433 chore(package-lock): update the package-lock.json
  packages/cactus-cockpit/package-lock.json
Labels: dependencies
