Repository hyperledger-cacti/cacti, pull requests merged in 2020-07, with the labels that each got.

#202 feat(api-server): TLS, mTLS support
  package.json
  packages/cactus-cmd-api-server/package-lock.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
  packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
  packages/cactus-cmd-api-server/src/main/typescript/config/self-signed-pki-generator.ts
  packages/cactus-cmd-api-server/src/main/typescript/public-api.ts
  packages/cactus-cmd-api-server/src/test/typescript/unit/config/self-signed-certificate-generator/certificates-work-for-mutual-tls-test.ts
  packages/cactus-cmd-api-server/src/test/typescript/unit/config/self-signed-certificate-generator/generates-working-certificates-test.ts
  packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-via-web-service.ts
  packages/cactus-test-plugin-web-service-consortium/src/test/typescript/integration/plugin-web-service-consortium/security-isolation-via-api-server-ports.ts
Labels: API_Server, Security, dependencies, enhancement

#203 style(tslint): ban PascalCase variables from the code
  tslint.json
Labels: Developer_Experience

#172 docs(build-md): add file to build project for contributors (not users)
  BUILD.md
Labels: Developer_Experience, documentation

#194 docs(contributing): add directory structure
  CONTRIBUTING.md
Labels: Developer_Experience, documentation
