Repository hyperledger-cacti/cacti, pull requests merged in 2020-10, with the labels that each got.

#277 feat(test-tooling): Containers class ls() and exec() methods
  packages/cactus-test-tooling/src/main/typescript/common/containers.ts
Labels: enhancement

#289 docs(contributing-md): explain the importance of reproducible builds
  CONTRIBUTING.md
Labels: dependencies, documentation

#291 chore(commitlint): husky to run commitlint in pre-commit hooks
  commitlint.config.js
  package.json
Labels: Developer_Experience, Nice-to-Have, enhancement, good first issue

#294 chore(security): add CodeQL analysis workflow
  codeql-analysis.yml
Labels: Security

#287 chore(package-json): fix npm audit security warnings
  package-lock.json
  package.json
  packages/cactus-cmd-api-server/package-lock.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cockpit/package-lock.json
  packages/cactus-cockpit/package.json
  packages/cactus-common/package.json
  packages/cactus-core-api/package.json
  packages/cactus-plugin-consortium-manual/package-lock.json
  packages/cactus-plugin-consortium-manual/package.json
  packages/cactus-plugin-keychain-memory/package.json
  packages/cactus-plugin-kv-storage-memory/package.json
  packages/cactus-plugin-ledger-connector-besu/package-lock.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-quorum/package-lock.json
  packages/cactus-plugin-ledger-connector-quorum/package.json
  packages/cactus-sdk/package.json
  packages/cactus-test-plugin-consortium-manual/package-lock.json
  packages/cactus-test-plugin-consortium-manual/package.json
  packages/cactus-test-plugin-ledger-connector-quorum/package-lock.json
  packages/cactus-test-plugin-ledger-connector-quorum/package.json
  packages/cactus-test-tooling/package-lock.json
  packages/cactus-test-tooling/package.json
Labels: Security

#322 docs(whitepaper): update the section of Ledger Plugin API
  whitepaper/whitepaper.md
Labels: documentation

#298 docs(whitepaper): refactor sequence diagram
  whitepaper/communication-protocol-between-blp-and-lp.png
  whitepaper/communication-protocol-between-blp-and-lp.puml
  whitepaper/whitepaper.md
Labels: documentation

#325 fix: missed references of cactus-sdk during rename in previous PR
  package.json
  tslint.json
Labels: bug
