Repository hyperledger-cacti/cacti, pull requests merged in 2020-06, with the labels that each got.

#166 docs(whitepaper): fix makefile and html+pdf toolchain
  whitepaper/Makefile
Labels: Developer_Experience, bug, dependencies, documentation

#169 docs(contributing-md): PR checklist, git guidance
  CONTRIBUTING.md
Labels: Developer_Experience, documentation

#177 Add video link to docs
  README.md
Labels: documentation

#168 docs(whitepaper): fix use case 2.7 diagram typo
  whitepaper/use-case-sequence-diagram-end-user-wallet-authentication-authorization.png
  whitepaper/use-case-sequence-diagram-end-user-wallet-authentication-authorization.puml
  whitepaper/whitepaper.md
Labels: documentation

#175 feat(common): add utility class Strings with replaceAll
  packages/cactus-common/src/main/typescript/public-api.ts
  packages/cactus-common/src/main/typescript/strings.ts
Labels: Developer_Experience, enhancement

#173 build(package-json): upgrade to Typescript v3.9.3 to have export/impo…
  package-lock.json
  package.json
Labels: dependencies

#162 test(test-tooling): add Containers utility class
  packages/cactus-test-tooling/package.json
  packages/cactus-test-tooling/src/main/typescript/common/containers.ts
  packages/cactus-test-tooling/src/main/typescript/http-echo/http-echo-container.ts
  packages/cactus-test-tooling/src/main/typescript/public-api.ts
  packages/cactus-test-tooling/src/test/typescript/integration/common/containers.test.ts
Labels: Developer_Experience, Nice-to-Have

#180 docs: white paper id spec
  whitepaper/whitepaper.md
Labels: documentation

#174 chore(cockpit): Angular 9, API URL injection
  packages/cactus-cockpit/angular.json
  packages/cactus-cockpit/package-lock.json
  packages/cactus-cockpit/package.json
  packages/cactus-cockpit/src/app/app.component.ts
  packages/cactus-cockpit/src/app/app.module.ts
  packages/cactus-cockpit/src/constants.ts
  packages/cactus-cockpit/tsconfig.app.json
Labels: Developer_Experience, dependencies

#179 docs(whitepaper): add a section of APIs and communication protocols
  whitepaper/communication-protocol-between-blp-and-lp.png
  whitepaper/communication-protocol-between-blp-and-lp.puml
  whitepaper/whitepaper.md
Labels: documentation

#206 docs(contributing-md): test automation/execution, SDK build
  CONTRIBUTING.md
Labels: documentation

#205 docs(governance): due process for PRs in order of submission
  GOVERNANCE.md
Labels: documentation

#213 fix(sdk): ignore and delete the unused git_push.sh file
  packages/cactus-sdk/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator-ignore
  packages/cactus-sdk/src/main/typescript/generated/openapi/typescript-axios/git_push.sh
Labels: bug, dependencies

#204 docs(contributing-md): github Desktop on Windows know about the file …
  CONTRIBUTING.md
Labels: Developer_Experience, documentation

#210 fix(cmd-api-server): disallow running on older than Node 12 but provi…
  .travis.yml
  packages/cactus-cmd-api-server/package-lock.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
  packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
Labels: Security, dependencies
