Repository hyperledger-cacti/cacti, pull requests merged in 2021-07, with the labels that each got.

#1092 ci(tools): ci.sh prints disk usage between test runs
  tools/ci.sh
Labels: Developer_Experience

#1093 test: migrate AIO images to the GitHub Container Registry
  examples/cactus-example-carbon-accounting-backend/src/main/typescript/infrastructure/carbon-accounting-app-dummy-infrastructure.ts
  examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
  packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
  packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
Labels: Developer_Experience

#1094 test: call pruneDockerAllIfGithubAction in test.onFinish handler
  examples/cactus-example-carbon-accounting-backend/src/test/typescript/integration/admin-enroll-v1-endpoint.test.ts
  examples/cactus-example-supply-chain-backend/src/test/typescript/integration/supply-chain-backend-api-calls.test.ts
  examples/cactus-example-supply-chain-backend/src/test/typescript/integration/supply-chain-cli-via-npm-script.test.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json.test.ts
  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts
  packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/initialize-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/new-contract-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/refund-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/withdraw-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/withdraw-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/withdraw-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/sign-transaction-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-via-web-service.test.ts
  packages/cactus-test-tooling/package-lock.json
  packages/cactus-test-tooling/package.json
  packages/cactus-test-tooling/src/main/typescript/common/containers.ts
  packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-bundler.test.ts
Labels: Developer_Experience

#1095 test(test-tooling): containers#pruneDockerResources prints disk usage
  packages/cactus-test-tooling/src/main/typescript/common/containers.ts
Labels: Developer_Experience

#1106 fix(connector-corda): kotlin compilation error due to missing method
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
Labels: Corda, bug

#1105 docs(examples): migrate containers to ubuntu-20.04 Docker-in-Docker
  .dockerignore
  README.md
  examples/carbon-accounting/Dockerfile
  examples/carbon-accounting/supervisord.conf
  examples/supply-chain-app/Dockerfile
  examples/supply-chain-app/README.md
  examples/supply-chain-app/supervisord.conf
  packages/cactus-cmd-api-server/package-lock.json
  packages/cactus-cmd-api-server/package.json
Labels: Developer_Experience, bug, dependencies, documentation

#1032 feat(core-api): add plugin object store interface definition
  packages/cactus-core-api/package-lock.json
  packages/cactus-core-api/src/main/json/openapi.json
  packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-core-api/src/main/typescript/plugin/object-store/i-plugin-object-store.ts
  packages/cactus-core-api/src/main/typescript/plugin/object-store/is-i-plugin-object-store.ts
  packages/cactus-core-api/src/main/typescript/public-api.ts
Labels: Core_API, enhancement

#1115 build: add VSCode recommended extension for Mermaid syntax
  .devcontainer/devcontainer.json
  .vscode/extensions.json
Labels: Developer_Experience

#1007 feat(plugin-object-store-ipfs): add IPFS plugin implementation
  extensions/cactus-plugin-object-store-ipfs/README.md
  extensions/cactus-plugin-object-store-ipfs/openapitools.json
  extensions/cactus-plugin-object-store-ipfs/package-lock.json
  extensions/cactus-plugin-object-store-ipfs/package.json
  extensions/cactus-plugin-object-store-ipfs/src/main/json/openapi.json
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator-ignore
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/FILES
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/generated/openapi/typescript-axios/api.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/generated/openapi/typescript-axios/base.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/generated/openapi/typescript-axios/common.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/generated/openapi/typescript-axios/configuration.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/generated/openapi/typescript-axios/index.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/i-ipfs-http-client.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/index.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/index.web.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/plugin-factory-object-store.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/plugin-object-store-ipfs.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/public-api.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/web-services/get-object-endpoint-v1.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/web-services/has-object-endpoint-v1.ts
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/web-services/set-object-endpoint-v1.ts
  extensions/cactus-plugin-object-store-ipfs/src/test/typescript/fixtures/mock/ipfs/ipfs-files-api-mock.ts
  extensions/cactus-plugin-object-store-ipfs/src/test/typescript/fixtures/mock/ipfs/ipfs-http-client-mock.ts
  extensions/cactus-plugin-object-store-ipfs/src/test/typescript/integration/api-surface.test.ts
  extensions/cactus-plugin-object-store-ipfs/src/test/typescript/integration/plugin-object-store-ipfs.test.ts
  extensions/cactus-plugin-object-store-ipfs/src/test/typescript/unit/api-surface.test.ts
  extensions/cactus-plugin-object-store-ipfs/src/test/typescript/unit/plugin-object-store-ipfs.test.ts
  extensions/cactus-plugin-object-store-ipfs/tsconfig.json
  lerna.json
  packages/cactus-cmd-api-server/package-lock.json
Labels: enhancement

#1127 fix: fixing branch name for code cov badge
  README.md
Labels: Developer_Experience, documentation

#1121 ci(github): add commit lint action to PRs
  .github/workflows/commitlint-pull-request.yml
Labels: Developer_Experience, dependencies

#1128 docs(whitepaper): add suggested reference
  whitepaper/whitepaper.md
Labels: documentation

#1124 refactor(connector-fabric): upgrade to Fabric 2.x Node SDK #1123
  examples/cactus-example-carbon-accounting-backend/package-lock.json
  examples/cactus-example-carbon-accounting-backend/package.json
  examples/cactus-example-supply-chain-backend/package-lock.json
  examples/cactus-example-supply-chain-backend/package.json
  packages/cactus-plugin-ledger-connector-fabric/package-lock.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
  packages/cactus-test-tooling/package-lock.json
  packages/cactus-test-tooling/package.json
  packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
Labels: Fabric, Security, enhancement

#1151 fix(connector-corda): fix build broken by operationId rename
  packages/cactus-cmd-api-server/README.md
  packages/cactus-plugin-consortium-manual/README.md
  packages/cactus-plugin-keychain-memory/README.md
  packages/cactus-plugin-keychain-vault/README.md
  packages/cactus-plugin-ledger-connector-besu/README.md
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
  packages/cactus-plugin-ledger-connector-quorum/README.md
  packages/cactus-plugin-ledger-connector-xdai/README.md
Labels: Corda, documentation

#1132 feat(connector-fabric): identity json signing credentials #1130
  packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/common/create-gateway.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
Labels: Fabric, enhancement

#1102 feat(besu): record locator
  packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-besu-record-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-record-locator.test.ts
Labels: Besu, enhancement

#1152 docs(examples): increase supply chain image boot responsiveness #780
  README.md
  examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
  examples/supply-chain-app/README.md
  packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
  packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
Labels: Developer_Experience, documentation

#1136 docs(examples): supply chain- eliminate endpoint constant classes
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/json/openapi.json
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bamboo-harvest-endpoint-constants.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bamboo-harvest-endpoint.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bookshelf-endpoint-constants.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bookshelf-endpoint.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bamboo-harvest-endpoint-constants.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bamboo-harvest-endpoint.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bookshelf-endpoint-constants.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bookshelf-endpoint.ts
Labels: Developer_Experience

#1133 feat(connector-fabric): endorsing peers request arg #1122
  .cspell.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
  yarn.lock
Labels: Fabric, enhancement

#1017 feat(google-sm): added keychain plugin for google secret manager
  packages/cactus-plugin-keychain-google-sm/README.md
  packages/cactus-plugin-keychain-google-sm/openapitools.json
  packages/cactus-plugin-keychain-google-sm/package.json
  packages/cactus-plugin-keychain-google-sm/src/main/json/openapi.json
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator-ignore
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/FILES
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/generated/openapi/typescript-axios/base.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/generated/openapi/typescript-axios/common.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/generated/openapi/typescript-axios/configuration.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/generated/openapi/typescript-axios/index.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/index.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/index.web.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/plugin-factory-keychain.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/plugin-keychain-google-sm.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/public-api.ts
  packages/cactus-plugin-keychain-google-sm/src/test/typescript/integration/plugin-keychain-google-sm.test.ts
  packages/cactus-plugin-keychain-google-sm/src/test/typescript/mock/plugin-keychain-google-sm-mock.ts
  packages/cactus-plugin-keychain-google-sm/src/test/typescript/unit/api-surface.test.ts
  packages/cactus-plugin-keychain-google-sm/tsconfig.json
  tsconfig.json
Labels: Keychain, enhancement

#1166 build(deps): fix sync-npm-deps-to-tsc-projects tool
  examples/cactus-example-carbon-accounting-backend/tsconfig.json
  examples/cactus-example-carbon-accounting-business-logic-plugin/tsconfig.json
  examples/cactus-example-supply-chain-backend/tsconfig.json
  examples/cactus-example-supply-chain-business-logic-plugin/tsconfig.json
  extensions/cactus-plugin-object-store-ipfs/tsconfig.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cmd-api-server/tsconfig.json
  packages/cactus-core-api/tsconfig.json
  packages/cactus-plugin-consortium-manual/tsconfig.json
  packages/cactus-plugin-htlc-eth-besu-erc20/tsconfig.json
  packages/cactus-plugin-htlc-eth-besu/tsconfig.json
  packages/cactus-plugin-keychain-aws-sm/tsconfig.json
  packages/cactus-plugin-keychain-azure-kv/tsconfig.json
  packages/cactus-plugin-keychain-google-sm/tsconfig.json
  packages/cactus-plugin-keychain-memory/tsconfig.json
  packages/cactus-plugin-keychain-vault/tsconfig.json
  packages/cactus-plugin-ledger-connector-besu/tsconfig.json
  packages/cactus-plugin-ledger-connector-corda/tsconfig.json
  packages/cactus-plugin-ledger-connector-fabric/tsconfig.json
  packages/cactus-plugin-ledger-connector-quorum/tsconfig.json
  packages/cactus-plugin-ledger-connector-xdai/tsconfig.json
  packages/cactus-test-plugin-htlc-eth-besu-erc20/tsconfig.json
  packages/cactus-test-plugin-htlc-eth-besu/tsconfig.json
  packages/cactus-test-plugin-ledger-connector-quorum/tsconfig.json
  tools/sync-npm-deps-to-tsc-projects.ts
  tsconfig.json
  yarn.lock
Labels: Developer_Experience, dependencies
