Repository hyperledger-cacti/cacti, pull requests merged in 2021-08, with the labels that each got.

#1173 refactor(core-api): keychain plugin get/set generics
  examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/typescript/business-logic-plugin/carbon-accounting-plugin.ts
  examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
  packages/cactus-core-api/src/main/typescript/plugin/keychain/i-plugin-keychain.ts
  packages/cactus-plugin-keychain-aws-sm/src/main/typescript/plugin-keychain-aws-sm.ts
  packages/cactus-plugin-keychain-azure-kv/src/main/typescript/plugin-keychain-azure-kv.ts
  packages/cactus-plugin-keychain-google-sm/src/main/typescript/plugin-keychain-google-sm.ts
  packages/cactus-plugin-keychain-memory/src/main/typescript/plugin-keychain-memory.ts
  packages/cactus-plugin-keychain-memory/src/test/typescript/unit/plugin-keychain-memory.test.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault-remote-adapter.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/besu-get-transaction.test.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-balance.test.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-block.test.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-past-logs.test.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-record-locator.test.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/invoke-contract.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/common/create-gateway.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-invoke-contract.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts
  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts
  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/invoke-contract-xdai.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/initialize-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/new-contract-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/refund-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/withdraw-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/withdraw-endpoint-invalid.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/withdraw-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-via-web-service.test.ts
Labels: Core_API, Keychain

#1178 build(tools): script to check OAS extensions #489
  package.json
  tools/ci.sh
  tools/custom-checks/check-open-api-json-specs.ts
  tools/custom-checks/has-property.ts
  tools/custom-checks/is-std-lib-record.ts
  tools/custom-checks/run-custom-checks.ts
Labels: Developer_Experience, dependencies

#1179 ci(tools): validate bundle names packages
  packages/cactus-cmd-api-server/package.json
  tools/ci.sh
  tools/validate-bundle-names.js
Labels: Developer_Experience, dependencies

#1184 build: yarnrc --ignore-engines true
  .yarnrc
  package.json
Labels: Developer_Experience, dependencies

#1177 docs(contributing.md): do not duplicate pull requests
  CONTRIBUTING.md
Labels: documentation, Developer_Experience

#1185 build(package.json): add reset script that git cleans prior to configure
  package.json
Labels: dependencies, Developer_Experience

#1203 fix(prometheus): metrics.ts leaks to global registry #1202
  packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
  packages/cactus-cmd-api-server/src/main/typescript/prometheus-exporter/metrics.ts
  packages/cactus-cmd-api-server/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/prometheus-exporter/metrics.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
  packages/cactus-plugin-keychain-memory/src/main/typescript/plugin-keychain-memory.ts
  packages/cactus-plugin-keychain-memory/src/main/typescript/prometheus-exporter/metrics.ts
  packages/cactus-plugin-keychain-memory/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/prometheus-exporter/metrics.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/prometheus-exporter/metrics.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/plugin-ledger-connector-corda.ts
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/prometheus-exporter/metrics.ts
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/prometheus-exporter/metrics.ts
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/prometheus-exporter/metrics.ts
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
Labels: bug

#1205 test(cmd-api-server): randomize port in config service test
  packages/cactus-cmd-api-server/src/test/typescript/unit/config/config-service-example-config-validity.test.ts
Labels: bug, API_Server

#1198 refactor(plugin-registry): getOneById to use instanceId #1197
  packages/cactus-core/src/main/typescript/plugin-registry.ts
  packages/cactus-core/src/test/typescript/unit/plugin-registry.test.ts
Labels: Developer_Experience

#1201 fix(plugin-consortium-manual): drop repo constructor arg #1199
  examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
  packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts
  packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
  packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
  packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/security-isolation-via-api-server-ports.ts
Labels: bug

#1204 fix(cmd-api-server): plugins interfere with API server deps #1192
  .cspell.json
  package.json
  packages/cactus-cmd-api-server/Dockerfile
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
  packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
  packages/cactus-cmd-api-server/src/test/typescript/benchmark/artillery-api-benchmark.test.ts
  packages/cactus-cmd-api-server/src/test/typescript/integration/jwt-endpoint-authorization.test.ts
  packages/cactus-cmd-api-server/src/test/typescript/integration/remote-plugin-imports.test.ts
  packages/cactus-cmd-api-server/src/test/typescript/unit/config/config-service-example-config-validity.test.ts
  packages/cactus-cmd-api-server/src/test/typescript/unit/plugins/install-basic-plugin-consortium-manual.test.ts
  packages/cactus-cmd-api-server/src/test/typescript/unit/plugins/install-basic-plugin-keychain-memory.test.ts
  packages/cactus-cmd-api-server/src/test/typescript/unit/plugins/install-basic-plugin-ledger-connector-fabric-0-7-0.test.ts
  packages/cactus-cmd-api-server/src/test/typescript/unit/plugins/install-basic-plugin-ledger-connector-quorum-0-7-0.test.ts
  packages/cactus-cmd-api-server/tsconfig.json
  packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts
  packages/cactus-test-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
  yarn.lock
Labels: bug, API_Server, dependencies, Security

#1175 docs: fix naming - use API Client instead of SDK
  CONTRIBUTING.md
  whitepaper/whitepaper.md
Labels: documentation

#1219 test(tools): besu multi-party AIO container image
  packages/cactus-test-tooling/src/main/typescript/besu/besu-mp-test-ledger.ts
  tools/docker/besu-multi-party-all-in-one/Dockerfile
  tools/docker/besu-multi-party-all-in-one/README.md
  tools/docker/besu-multi-party-all-in-one/healthcheck.sh
  tools/docker/besu-multi-party-all-in-one/hooks/post_push
  tools/docker/besu-multi-party-all-in-one/supervisord.conf
Labels: enhancement, Besu, dependencies, Developer_Experience

#1228 fix(cmd-api-server): add missing deps remove unused ones #1226
  packages/cactus-cmd-api-server/package.json
  yarn.lock
Labels: bug, API_Server, dependencies

#1221 test: ensure .test suffix on mTLS tests
  packages/cactus-cmd-api-server/src/test/typescript/unit/config/self-signed-certificate-generator/certificates-work-for-mutual-tls.test.ts
  packages/cactus-cmd-api-server/src/test/typescript/unit/config/self-signed-certificate-generator/generates-working-certificates.test.ts
Labels: Developer_Experience

#1225 fix(examples): front-end packages missing browserify polyfills #1224
  examples/cactus-example-carbon-accounting-frontend/.browserslistrc
  examples/cactus-example-carbon-accounting-frontend/angular.json
  examples/cactus-example-carbon-accounting-frontend/package.json
  examples/cactus-example-carbon-accounting-frontend/webpack.config.overrides.js
  examples/cactus-example-supply-chain-frontend/.browserslistrc
  examples/cactus-example-supply-chain-frontend/angular.json
  examples/cactus-example-supply-chain-frontend/package.json
  examples/cactus-example-supply-chain-frontend/webpack.config.overrides.js
  webpack.dev.web.js
  webpack.prod.web.js
  yarn.lock
Labels: bug, dependencies, Developer_Experience

#1240 docs: update faq documentation and incorporate Quick-Start-Topics section
  FAQ.md
Labels: documentation

#1242 docs(tools): fix besu all-in-one docker-compose #1241
  tools/docker/besu-all-in-one/docker-compose.yml
Labels: documentation, Besu, dependencies

#1270 build(dev-container): fix yarn not found error #1269
  .devcontainer/Dockerfile
  .devcontainer/post-create-commands.sh
Labels: bug, dependencies, Developer_Experience

#1169 feat(connector-iroha): adds connector plugin
  .cspell.json
  docs/source/support/iroha.md
  package.json
  packages/cactus-common/src/main/typescript/http/http-status-code-errors.ts
  packages/cactus-common/src/main/typescript/public-api.ts
  packages/cactus-plugin-ledger-connector-iroha/Dockerfile
  packages/cactus-plugin-ledger-connector-iroha/README.md
  packages/cactus-plugin-ledger-connector-iroha/docs/architecture/images/run-transaction-endpoint-transact.png
  packages/cactus-plugin-ledger-connector-iroha/docs/architecture/images/run-transaction-endpoint.png
  packages/cactus-plugin-ledger-connector-iroha/docs/architecture/run-transaction-endpoint-transact.puml
  packages/cactus-plugin-ledger-connector-iroha/docs/architecture/run-transaction-endpoint.puml
  packages/cactus-plugin-ledger-connector-iroha/openapitools.json
  packages/cactus-plugin-ledger-connector-iroha/package.json
  packages/cactus-plugin-ledger-connector-iroha/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator-ignore
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/FILES
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/base.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/common.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/configuration.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/index.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/index.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/index.web.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/plugin-factory-ledger-connector.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/plugin-ledger-connector-iroha.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/prometheus-exporter/data-fetcher.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/prometheus-exporter/metrics.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/prometheus-exporter/response.type.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/public-api.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/web-services/run-transaction-endpoint.ts
  packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/api-surface.test.ts
  packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/iroha-iroha-transfer-example.test.ts
  packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/unit/api-surface.test.ts
  packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/unit/iroha-test-ledger-parameters.test.ts
  packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/unit/postgres-test-container-parameters.test.ts
  packages/cactus-plugin-ledger-connector-iroha/tsconfig.json
  packages/cactus-test-tooling/src/main/typescript/iroha/iroha-test-ledger.ts
  tsconfig.json
  webpack.prod.node.js
Labels: enhancement, Iroha

#1278 fix(cactus-core-api): integrate check for req function onPluginInit into isCactusPlugin function
  packages/cactus-core-api/src/main/typescript/plugin/i-cactus-plugin.ts
Labels: bug, Core_API

#1243 feat(connector-fabric): add support for vault transit secret engine
  .cspell.json
  packages/cactus-plugin-ledger-connector-fabric/README.md
  packages/cactus-plugin-ledger-connector-fabric/docs/architecture/images/run-transaction-endpoint-enroll.png
  packages/cactus-plugin-ledger-connector-fabric/docs/architecture/run-transaction-endpoint-enroll.puml
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/common/create-gateway.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/identity/identity-provider.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/identity/internal/cert-datastore.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/identity/internal/client.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/identity/internal/crypto-suite.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/identity/internal/crypto-util.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/identity/internal/key.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/identity/vault-client.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/public-api.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-identities.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/identity-client.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/unit/identity-internal-crypto-utils.test.ts
  packages/cactus-test-tooling/src/main/typescript/common/containers.ts
  yarn.lock
Labels: documentation, enhancement, Fabric, dependencies, Security, Keychain
