Repository hyperledger-cacti/cacti, pull requests merged in 2021-09, with the labels that each got.

#1145 style: fix openAPI spec linter warning endpoints
  examples/cactus-example-carbon-accounting-backend/src/main/typescript/infrastructure/carbon-accounting-app-dummy-infrastructure.ts
  packages/cactus-core-api/src/main/typescript/public-api.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-consortium-jws-endpoint-v1.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-node-jws-endpoint-v1.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-prometheus-exporter-metrics-endpoint-v1.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/public-api.ts
  packages/cactus-plugin-htlc-eth-besu-erc20/src/main/typescript/web-services/get-single-status-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu-erc20/src/main/typescript/web-services/get-status-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu-erc20/src/main/typescript/web-services/initialize-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu-erc20/src/main/typescript/web-services/new-contract-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu-erc20/src/main/typescript/web-services/refund-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu-erc20/src/main/typescript/web-services/withdraw-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu/src/main/typescript/public-api.ts
  packages/cactus-plugin-htlc-eth-besu/src/main/typescript/web-services/get-single-status-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu/src/main/typescript/web-services/get-status-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu/src/main/typescript/web-services/initialize-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu/src/main/typescript/web-services/new-contract-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu/src/main/typescript/web-services/refund-endpoint.ts
  packages/cactus-plugin-htlc-eth-besu/src/main/typescript/web-services/withdraw-endpoint.ts
  packages/cactus-plugin-keychain-memory/src/main/typescript/get-prometheus-exporter-metrics/get-prometheus-exporter-metrics-endpoint-v1.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/delete-keychain-entry-endpoint-v1.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/get-keychain-entry-endpoint-v1.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint-v1.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/has-keychain-entry-endpoint-v1.ts
  packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/set-keychain-entry-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/deploy-contract-solidity-bytecode-endpoint.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-balance-endpoint.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-block-v1-endpoint-.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-past-logs-endpoint.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-transaction-endpoint.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/invoke-contract-endpoint.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/run-transaction-endpoint.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/sign-transaction-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/web-services/deploy-contract-jars-endpoint.ts
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/web-services/invoke-contract-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-source/deploy-contract-go-source-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract/deploy-contract-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/get-prometheus-exporter-metrics/get-prometheus-exporter-metrics-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/run-transaction/run-transaction-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/web-services/deploy-contract-solidity-bytecode-endpoint.ts
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/web-services/invoke-contract-endpoint.ts
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/web-services/run-transaction-endpoint.ts
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/web-services/deploy-contract-solidity-bytecode-endpoint.ts
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint-v1.ts
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/web-services/invoke-contract-endpoint.ts
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/web-services/run-transaction-endpoint.ts
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint-invalid.test.ts
Labels: enhancement, Developer_Experience

#1209 docs(ci): support debugging on CI server through ssh
  BUILD.md
Labels: documentation

#1300 fix(test): flaky fabric AIO container boot #876
  examples/cactus-example-carbon-accounting-backend/src/main/typescript/infrastructure/carbon-accounting-app-dummy-infrastructure.ts
  examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-identities.test.ts
  packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
  tools/docker/fabric-all-in-one/supervisord.conf
Labels: bug, Fabric, dependencies, Developer_Experience

#1285 feat(corda): support corda v4.8 #889
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes-v4.8.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server-v4.8.test.ts
  tools/docker/corda-all-in-one/README.md
  tools/docker/corda-all-in-one/corda-v4_8/Dockerfile
Labels: enhancement, Corda

#1282 docs(roadmap): update ROADMAP.md - 2021 August #1280
  ROADMAP.md
Labels: documentation

#1318 docs(dev-container): fix Unable to access jarfile openapi-generator-c…
  examples/cactus-example-carbon-accounting-business-logic-plugin/openapitools.json
  examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/typescript/generated/openapi/typescript-axios/api.ts
  examples/cactus-example-supply-chain-business-logic-plugin/openapitools.json
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  extensions/cactus-plugin-object-store-ipfs/openapitools.json
  extensions/cactus-plugin-object-store-ipfs/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-cmd-api-server/openapitools.json
  packages/cactus-cmd-api-server/src/main/proto/generated/openapi/.openapi-generator/VERSION
  packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-core-api/openapitools.json
  packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-consortium-manual/openapitools.json
  packages/cactus-plugin-consortium-manual/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-htlc-eth-besu-erc20/openapitools.json
  packages/cactus-plugin-htlc-eth-besu-erc20/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-htlc-eth-besu-erc20/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-htlc-eth-besu/openapitools.json
  packages/cactus-plugin-htlc-eth-besu/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-htlc-eth-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-keychain-memory/openapitools.json
  packages/cactus-plugin-keychain-memory/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-keychain-vault/openapitools.json
  packages/cactus-plugin-keychain-vault/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-ledger-connector-besu/openapitools.json
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-corda/openapitools.json
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/.openapi-generator/VERSION
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-fabric/openapitools.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-iroha/openapitools.json
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-quorum/openapitools.json
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-xdai/openapitools.json
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/generated/openapi/typescript-axios/api.ts
Labels: bug, documentation

#1335 ci: re-enable image caching, skip flaky tests #1334
  .cspell.json
  .github/workflows/ci.yml
  package.json
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/iroha-iroha-transfer-example.test.ts
  packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts
  packages/cactus-test-tooling/src/main/typescript/github-actions/is-running-in-github-action.ts
  packages/cactus-test-tooling/src/test/typescript/integration/iroha/iroha-test-ledger/constructor-validates-options.test.ts
Labels: dependencies, Developer_Experience

#1323 chore(deps): upgrade Web3 to v1.5.2
  examples/cactus-example-carbon-accounting-backend/package.json
  examples/cactus-example-supply-chain-backend/package.json
  packages/cactus-plugin-htlc-eth-besu/package.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-quorum/package.json
  packages/cactus-plugin-ledger-connector-xdai/package.json
  packages/cactus-test-api-client/package.json
  packages/cactus-test-plugin-htlc-eth-besu/package.json
  packages/cactus-test-plugin-ledger-connector-besu/package.json
  packages/cactus-test-plugin-ledger-connector-quorum/package.json
  packages/cactus-test-tooling/package.json
  yarn.lock
Labels: dependencies, Security

#1343 build(yarn): reset script now wipes node modules, yarn lock
  package.json
  yarn.lock
Labels: dependencies, Developer_Experience

#1342 ci: set the swap file size to 10 GB for GitHub runners
  .github/workflows/ci.yml
Labels: dependencies

#1345 build(deps): upgrade axios to latest to fix CVE
  examples/cactus-example-carbon-accounting-business-logic-plugin/package.json
  examples/cactus-example-supply-chain-backend/package.json
  examples/cactus-example-supply-chain-business-logic-plugin/package.json
  extensions/cactus-plugin-object-store-ipfs/package.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-core-api/package.json
  packages/cactus-plugin-consortium-manual/package.json
  packages/cactus-plugin-htlc-eth-besu-erc20/package.json
  packages/cactus-plugin-htlc-eth-besu/package.json
  packages/cactus-plugin-keychain-aws-sm/package.json
  packages/cactus-plugin-keychain-azure-kv/package.json
  packages/cactus-plugin-keychain-google-sm/package.json
  packages/cactus-plugin-keychain-memory/package.json
  packages/cactus-plugin-keychain-vault/package.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-corda/package.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-iroha/package.json
  packages/cactus-plugin-ledger-connector-quorum/package.json
  packages/cactus-plugin-ledger-connector-xdai/package.json
  packages/cactus-test-plugin-consortium-manual/package.json
  packages/cactus-test-plugin-htlc-eth-besu-erc20/package.json
  packages/cactus-test-plugin-htlc-eth-besu/package.json
  packages/cactus-test-tooling/package.json
  yarn.lock
Labels: dependencies, Security

#1284 docs(connector-iroha): add Iroha menu item in the ledger support matrix
  docs/source/support.rst
Labels: documentation, Iroha

#1107 ci(containerization): build all container images via the CI suite #942
  .github/workflows/ci.yml
  examples/cactus-example-carbon-accounting-backend/package.json
  examples/carbon-accounting/Dockerfile
  packages/cactus-cmd-api-server/Dockerfile
  packages/cactus-plugin-ledger-connector-besu/Dockerfile
  packages/cactus-plugin-ledger-connector-fabric/Dockerfile
Labels: dependencies, Developer_Experience

#1376 ci: drop Node v12 from matrix
  .github/workflows/ci.yml
Labels: dependencies, Developer_Experience

#1332 fix: openapi validation test for iroha plugin
  packages/cactus-plugin-ledger-connector-iroha/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/openapi/openapi-validation.test.ts
  packages/cactus-test-tooling/src/test/typescript/integration/iroha/iroha-test-ledger/constructor-validates-options.test.ts
Labels: Iroha
