Repository hyperledger-cacti/cacti, pull requests merged in 2021-11, with the labels that each got.

#1486 test: skip corda deploy 4.6 integration test
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts
Labels: Corda, Developer_Experience, Flaky-Test-Automation, Tests

#1511 docs(tools): fix/migrate example config generator to ESM
  tools/generate-api-server-config.js
Labels: bug, documentation, dependencies, Developer_Experience

#1529 ci(dci-lint): git refusing to fetch into current branch #1440
  .github/workflows/ci.yml
Labels: bug, dependencies, Developer_Experience, Tests, P3

#1533 fix(deps): sibling package dependencies keychain-memory 0.6.0 #1532
  packages/cactus-plugin-htlc-eth-besu/package.json
  packages/cactus-plugin-keychain-memory-wasm/package.json
  packages/cactus-plugin-odap-hermes/package.json
  packages/cactus-test-tooling/package-lock.json
Labels: bug, dependencies, Developer_Experience

#1538 test(fabric): update AIO image tags to 1.0.0-rc.2 to lower flakes #1537
  examples/cactus-example-carbon-accounting-backend/src/main/typescript/infrastructure/carbon-accounting-app-dummy-infrastructure.ts
  examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/add-orgs.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-lock-asset.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/obtain-profiles.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-identities.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-ws-ids.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/openapi/openapi-validation-go.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/openapi/openapi-validation.test.ts
  packages/cactus-plugin-odap-hermes/src/test/typescript/integration/odap/odap-api-call-with-ledger-connector.test.ts
  packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
Labels: bug, Fabric, Flaky-Test-Automation, Tests

#1541 chore(deps): upgrade @openapitools/openapi-generator-cli to latest
  package.json
  yarn.lock
Labels: bug, dependencies, Developer_Experience

#1535 ci: custom check to verify uniform sibling dependency versions #1534
  tools/custom-checks/check-sibling-dep-version-consistency.ts
  tools/custom-checks/run-custom-checks.ts
Labels: enhancement, dependencies, Developer_Experience

#1568 ci(tools): fix iroha AIO image build flake on CI
  .github/workflows/ci.yml
Labels: bug, dependencies, Developer_Experience, Iroha

#1554 chore: clean package.json
  package.json
Labels: enhancement, dependencies, Developer_Experience

#1564 fix(cmd-api-server): build occasionally broken - protoc-gen-ts #1563
  package.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cmd-api-server/src/main/typescript/generated/proto/protoc-gen-ts/google/protobuf/empty.ts
  packages/cactus-cmd-api-server/src/main/typescript/generated/proto/protoc-gen-ts/models/health_check_response_pb.ts
  packages/cactus-cmd-api-server/src/main/typescript/generated/proto/protoc-gen-ts/models/memory_usage_pb.ts
  packages/cactus-cmd-api-server/src/main/typescript/generated/proto/protoc-gen-ts/services/default_service.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/access_control.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/ack.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/asset_locks.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/asset_transfer.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/interop_payload.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/membership.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/proofs.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/query.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/state.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/common/verification_policy.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/corda/view_data.ts
  packages/cactus-core-api/src/main/typescript/generated/proto/protoc-gen-ts/weaver/common/protos/networks/networks.ts
  packages/cactus-plugin-ledger-connector-iroha/package.json
  yarn.lock
Labels: bug, API_Server, dependencies, Developer_Experience

#1560 feat(docs): upated maintainers list
  MAINTAINERS.md
Labels: documentation, P1

#1571 fix(security): remedy CVE-2021-3749
  extensions/cactus-plugin-htlc-coordinator-besu/package.json
  packages/cactus-plugin-odap-hermes/package.json
  yarn.lock
Labels: dependencies, Security, P1

#1572 fix(connector-fabric): chain code deployment fails >1 scp concurrency
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
  packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
Labels: bug, Fabric

#1576 test: jestify besu-get-transaction
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/besu-get-transaction.test.ts
Labels: Tests

#1577 test: jestify besu-test-ledger-parameters
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/besu-test-ledger-parameters.test.ts
Labels: Besu, Tests

#1565 build(deps): bump @openzeppelin/contracts from 4.2.0 to 4.3.3
  examples/cactus-example-carbon-accounting-backend/package.json
  yarn.lock
Labels: dependencies, Security

#1582 test: jestify drop-non-printable
  .taprc
  jest.config.js
  packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
Labels: Tests

#1584 test: jestify get-all-method-names test
  .taprc
  jest.config.js
  packages/cactus-common/src/test/typescript/unit/objects/get-all-method-names.test.ts
Labels: Tests

#1531 test: jestify v2141 deploy contract from json
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json.test.ts
Labels: Tests
