Repository hyperledger-cacti/cacti, pull requests merged in 2021-12, with the labels that each got.

#1588 test: jestify model-type-guards test
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/unit/model-type-guards.test.ts
Labels: Tests

#1589 test: jestify rustc-container-target-nodejs
  .taprc
  jest.config.js
  packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-nodejs.test.ts
Labels: Tests

#1601 fix(security): upgrade fabric-common to 2.2.10 or later
  contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/restserver/coreapi/lib/common/fabric_v1.0/package.json
  examples/cactus-example-carbon-accounting-backend/package.json
  examples/cactus-example-supply-chain-backend/package.json
  examples/cartrade/package.json
  examples/cartrade/script-test-getFunctions/fabric/package.json
  examples/cartrade/validatorDriver/package.json
  examples/discounted-cartrade/package.json
  examples/discounted-cartrade/script-test-getFunctions/fabric/package.json
  examples/discounted-cartrade/validatorDriver/package.json
  examples/electricity-trade/package.json
  examples/test-run-transaction/package.json
  packages/cactus-cmd-socketio-server/package.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/unit-test/package.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-test-tooling/package.json
  yarn.lock
Labels: Security, P1

#1592 feat(example): make cartrade support more environments
  tools/docker/fabric14-fabcar-testnet/fabric-samples_dockerize.patch
  tools/docker/fabric14-fabcar-testnet/how_to_containerize_fabcar.md
  tools/docker/fabric14-fabcar-testnet/script-start-docker_newer.patch
Labels: dependencies, Developer_Experience, Tests

#1586 test: jestify corda-test-ledger-constructor test
  .taprc
  jest.config.js
  packages/cactus-test-tooling/src/test/typescript/integration/corda/corda-test-ledger/corda-test-ledger-constructor.test.ts
Labels: Tests

#1594 test: jestify run transaction endpoint test
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
Labels: Tests

#1599 test: skip flaky deploy-cordapp-jars-to-nodes-v4.8-express
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes-v4.8-express.test.ts
Labels: bug, Corda, dependencies, Developer_Experience, Flaky-Test-Automation, Tests

#1585 test: jestify coded-error test
  packages/cactus-common/src/test/typescript/unit/coded-error.test.ts
Labels: Tests

#1623 fix(supply-chain-app): enable cockpit in supply-chain
  examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
Labels: bug, documentation, dependencies

#1546 test: jestify deploy-contract-from-json-xdai test
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts
Labels: Tests

#1618 test: jestify transfer-commence test
  .taprc
  jest.config.js
  packages/cactus-plugin-odap-hermes/src/test/typescript/integration/odap/transfer-commence.test.ts
Labels: Tests

#1547 test: jestify deploy-cc-from-golang-source-private-data test
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
Labels: Fabric, Tests

#1638 refactor(connector-fabric): deprecate chain code compiler
  .cspell.json
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-fabric/README.md
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/chain-code-compiler.ts
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/public-api.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/hello-world-contract-fabric-v14/hello-world-contract-go-mod.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/unit/chain-code-compiler.test.ts
Labels: documentation, Fabric

#1640 fix(security): upgrade web3 to upgrade elliptic > 6.5.4
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-odap-hermes/package.json
  yarn.lock
Labels: dependencies, Security, P1

#1548 test: jestify new-contract-endpoint test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/new-contract-endpoint.test.ts
Labels: Besu, Tests

#1575 test(cmd-socketio-server): add new unit test for cmd-socketio-server verifier
  jest.config.js
  packages/cactus-cmd-socketio-server/jest.config.js
  packages/cactus-cmd-socketio-server/package.json
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/util/__mocks__/ConfigUtil.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/DriverCommon.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/TestSocketHelpers.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/ValidatorAuthentication.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/Verifier.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/VerifierAuthentication.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/VerifierFactory.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/validator-registry.test.ts
Labels: Tests

#1578 test: jestify replace-all test
  .taprc
  jest.config.js
  packages/cactus-common/src/test/typescript/unit/strings/replace-all.test.ts
Labels: Tests

#1649 fix(config-service): faulty shutdownHook definition in the Config-Schema
  packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
Labels: bug, API_Server

#1655 fix(cmd-api-server): disable validateKeyPairMatch
  packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
Labels: bug, API_Server

#1583 test: jestify is-string test
  .taprc
  jest.config.js
  packages/cactus-common/src/test/typescript/unit/strings/is-string.test.ts
Labels: Tests

#1643 fix(plugin-odap-hermes): remove extraneous dependencies
  packages/cactus-plugin-odap-hermes/package.json
  packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/odap-gateway.ts
  yarn.lock
Labels: dependencies, Developer_Experience

#1663 fix: remove jade dependencies
  contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/appserver/serviceapi/package.json
  contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/restserver/coreapi/package.json
  examples/cartrade/package.json
  examples/discounted-cartrade/package.json
  examples/electricity-trade/package.json
  examples/test-run-transaction/package.json
  packages/cactus-cmd-socketio-server/package.json
Labels: dependencies, Security, P1

#1551 test: jestify invoke contract xdai test
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/invoke-contract-xdai.test.ts
Labels: Xdai, Tests, Jestify

#1561 feat(connector-corda): enable Flow Database Access CorDapp
  .cspell.json
  .github/workflows/ci.yml
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/build.gradle.kts
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/InvokeContractV1Response.kt
  packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes-v4.7.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes-v4.8-express.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes-v4.8.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/flow-database-access-v4.8.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server-v4.7.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server-v4.8.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
  packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/openapi/openapi-validation.test.ts
  packages/cactus-test-tooling/src/main/typescript/corda/corda-test-ledger.ts
  packages/cactus-test-tooling/src/main/typescript/corda/sample-cordapp-enum.ts
  packages/cactus-test-tooling/src/main/typescript/public-api.ts
  tools/docker/corda-all-in-one/README.md
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/Dockerfile
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/build.gradle
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/healthcheck.sh
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/run-notary-node.sh
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/run-party-a-node.sh
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/run-party-a-server.sh
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/run-party-b-node.sh
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/run-party-b-server.sh
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/run-party-c-node.sh
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/run-party-c-server.sh
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/supervisord.conf
Labels: bug, Corda

#1659 test: jestify get-all-field-names test
  .taprc
  jest.config.js
  packages/cactus-common/src/test/typescript/unit/objects/get-all-field-names.test.ts
Labels: Tests, Jestify

#1652 fix: config-service validator throws warnings
  packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
Labels: bug, API_Server

#1669 test: jestify config-service-example-config-validity test
  .taprc
  jest.config.js
  packages/cactus-cmd-api-server/src/test/typescript/unit/config/config-service-example-config-validity.test.ts
Labels: Tests, Jestify

#1668 test: jestify v2.3.0-invoke contract test
  .taprc
  jest.config.js
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-invoke-contract.test.ts
Labels: Tests, Jestify

#1681 test: jestify initialize-endpoint-invalid test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts
Labels: Tests, Jestify

#1682 test: jestify initialize-endpoint test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint.test.ts
Labels: Besu, Tests, Jestify

#1685 test: jestify get-node-jws-endpoint-v1 test
  .taprc
  jest.config.js
  packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts
Labels: Tests, Jestify

#1687 test: jestify new-contract-endpoint test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint.test.ts
Labels: Tests, Jestify

#1693 test: jestify refund-endpoint-invalid test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint-invalid.test.ts
Labels: Tests, Jestify

#1695 test: jestify withdraw-endpoint test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/withdraw-endpoint.test.ts
Labels: Tests, Jestify

#1539 build: migrate to GitHub Container Registry when it hits GA
  .github/workflows/besu-all-in-one-publish.yaml
  .github/workflows/cactus-whitepaper-publish.yaml
  .github/workflows/cmd-api-server-publish.yaml
  .github/workflows/connector-besu-publish.yaml
  .github/workflows/connector-corda-server-publish.yaml
  .github/workflows/connector-fabric-publish.yaml
  .github/workflows/corda-4-6-all-in-one-obligation-publish.yaml
  .github/workflows/corda-4-7-all-in-one-obligation-publish.yaml
  .github/workflows/corda-4-8-all-in-one-obligation-publish.yaml
  .github/workflows/dev-container-vscode-publish.yaml
  .github/workflows/example-carbon-accounting-publish.yaml
  .github/workflows/example-supply-chain-app-publish.yaml
  .github/workflows/fabric-all-in-one-publish.yaml
  .github/workflows/fabric2-all-in-one-publish.yaml
  .github/workflows/iroha-all-in-one-publish.yaml
  .github/workflows/keychain-vault-server-publish.yaml
  .github/workflows/quorum-all-in-one-publish.yaml
  .github/workflows/rust-compiler-publish.yaml
  .github/workflows/test-npm-registry-publish.yaml
  CONTRIBUTING.md
  examples/supply-chain-app/hooks/post_push
  packages/cactus-cmd-api-server/hooks/post_push
  packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/README.md
  packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/hooks/post_push
  packages/cactus-plugin-ledger-connector-corda/src/main-server/hooks/post_push
  packages/cactus-plugin-ledger-connector-fabric/README.md
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/openapi/openapi-validation-no-keychain.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/openapi/openapi-validation.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json-json-object-endpoints.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json-json-object.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-invoke-contract-json-object-endpoints.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-invoke-contract-json-object.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-invoke-contract.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json-json-object-endpoints.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json-json-object.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract-json-object-endpoints.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract-json-object.test.ts
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
  packages/cactus-test-tooling/src/main/typescript/cactus-keychain-vault-server/cactus-keychain-vault-server.ts
  tools/docker/besu-all-in-one/hooks/post_push
  tools/docker/besu-multi-party-all-in-one/hooks/post_push
  tools/docker/corda-all-in-one/hooks/post_push
  tools/docker/fabric-all-in-one/hooks/post_push
  tools/docker/quorum-all-in-one/hooks/post_push
  tools/docker/quorum-multi-party-all-in-one/hooks/post_push
  tools/docker/rust-compiler/hooks/post_push
  tools/docker/substrate-all-in-one/hooks/post_push
  tools/docker/test-npm-registry/README.md
Labels: dependencies, Developer_Experience

#1694 test: jestify initialize-endpoint test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/initialize-endpoint.test.ts
Labels: Tests, Jestify
