Repository hyperledger-cacti/cacti, pull requests merged in 2021-06, with the labels that each got.

#988 test(cmd-api-server): refactor mTLS test to use tape-promise
  packages/cactus-cmd-api-server/src/test/typescript/unit/config/self-signed-certificate-generator/certificates-work-for-mutual-tls-test.ts
Labels: Developer_Experience

#921 fix(cmd-api-server): config-service example - authorization JSON
  packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
  packages/cactus-cmd-api-server/src/test/typescript/unit/config/config-service-example-config-validity.test.ts
Labels: API_Server, bug

#932 refactor(connector-corda): consolidate transaction invocation API #611
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/InvokeContractV1Response.kt
  packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/generated/openapi/typescript-axios/api.ts
Labels: Corda

#925 chore(deps): upgrade to npm v7
  examples/cactus-example-carbon-accounting-backend/package-lock.json
  examples/cactus-example-carbon-accounting-business-logic-plugin/package-lock.json
  examples/cactus-example-carbon-accounting-frontend/package-lock.json
  examples/cactus-example-supply-chain-backend/package-lock.json
  examples/cactus-example-supply-chain-business-logic-plugin/package-lock.json
  examples/cactus-example-supply-chain-frontend/package-lock.json
  package-lock.json
  packages/cactus-cmd-api-server/package-lock.json
  packages/cactus-cockpit/package-lock.json
  packages/cactus-common/package-lock.json
  packages/cactus-core-api/package-lock.json
  packages/cactus-core/package-lock.json
  packages/cactus-plugin-consortium-manual/package-lock.json
  packages/cactus-plugin-htlc-eth-besu-erc20/package-lock.json
  packages/cactus-plugin-keychain-memory/package-lock.json
  packages/cactus-plugin-keychain-vault/package-lock.json
  packages/cactus-plugin-ledger-connector-besu/package-lock.json
  packages/cactus-plugin-ledger-connector-corda/package-lock.json
  packages/cactus-plugin-ledger-connector-fabric/package-lock.json
  packages/cactus-plugin-ledger-connector-quorum/package-lock.json
  packages/cactus-plugin-ledger-connector-xdai/package-lock.json
  packages/cactus-test-api-client/package-lock.json
  packages/cactus-test-cmd-api-server/package-lock.json
  packages/cactus-test-plugin-consortium-manual/package-lock.json
  packages/cactus-test-plugin-htlc-eth-besu-erc20/package-lock.json
  packages/cactus-test-plugin-ledger-connector-besu/package-lock.json
  packages/cactus-test-plugin-ledger-connector-quorum/package-lock.json
  packages/cactus-test-tooling/package-lock.json
  tools/ci.sh
Labels: dependencies

#936 chore(deps): npm audit fix --force 2021-05-06
  package-lock.json
  package.json
Labels: Security, dependencies

#996 build: migrate dev container to Ubuntu 20; add nvm to image
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post-create-commands.sh
Labels: Developer_Experience, dependencies

#1005 test(connector-fabric): upgrade Fabric AIO image tag used for test
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
Labels: Fabric

#918 refactor(supply-chain-backend): .test.ts suffix for api-surface tests
  examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
  examples/cactus-example-supply-chain-backend/src/main/typescript/public-api.ts
  examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app-cli.ts
  examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
  examples/cactus-example-supply-chain-backend/src/test/typescript/integration/supply-chain-backend-api-calls.test.ts
  examples/cactus-example-supply-chain-backend/src/test/typescript/integration/supply-chain-cli-via-npm-script.test.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/supply-chain-cactus-plugin.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-shipment-endpoint.ts
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-shipment-endpoint.ts
Labels: documentation

#1031 docs(contributing.md): explicit recommendation for avoiding global dependencies #585
  CONTRIBUTING.md
Labels: documentation

#1073 test(connector-fabric): fix v1.4.8 golang chaincode test
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/deploy-cc-from-golang-source.test.ts
Labels: bug, dependencies

#1021 style(linter): shipment-detail page linter fix
  examples/cactus-example-supply-chain-frontend/src/app/shipment/shipment-detail/shipment-detail.page.ts
Labels: Developer_Experience

#1037 test: add logLevel parameter to Fabric AIO ctor calls
  examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
Labels: Developer_Experience, SPIKE

#1076 test: fixed race in besu, quorum test ledger teardown logic
  packages/cactus-test-tooling/src/test/typescript/integration/besu/besu-test-ledger/constructor-validates-options.ts
  packages/cactus-test-tooling/src/test/typescript/integration/quorum/quorum-test-ledger/constructor-validates-options.ts
Labels: Besu, Quorum, bug

#1054 feat(test-tooling): add besu multi-party test ledger
  packages/cactus-test-tooling/src/main/typescript/besu/besu-mp-test-ledger.ts
  packages/cactus-test-tooling/src/main/typescript/public-api.ts
Labels: Besu

#1075 build(dev-container): use Node v16 & npm 7
  .devcontainer/Dockerfile
Labels: Developer_Experience

#1074 build(dev-container): add GVM (go version manager)
  .devcontainer/Dockerfile
Labels: Developer_Experience

#1047 feat(test-tooling): rust compiler container for wasm builds
  packages/cactus-cockpit/package-lock.json
  packages/cactus-test-tooling/package-lock.json
  packages/cactus-test-tooling/package.json
  packages/cactus-test-tooling/src/main/typescript/public-api.ts
  packages/cactus-test-tooling/src/main/typescript/rustc-container/rustc-build-cmd.ts
  packages/cactus-test-tooling/src/main/typescript/rustc-container/rustc-container.ts
  packages/cactus-test-tooling/src/test/rust/fixtures/wasm-hello-world/.gitignore
  packages/cactus-test-tooling/src/test/rust/fixtures/wasm-hello-world/Cargo.lock
  packages/cactus-test-tooling/src/test/rust/fixtures/wasm-hello-world/Cargo.toml
  packages/cactus-test-tooling/src/test/rust/fixtures/wasm-hello-world/src/lib.rs
  packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-bundler.test.ts
  packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-nodejs.test.ts
  tools/docker/rust-compiler/Dockerfile
  tools/docker/rust-compiler/README.md
  tools/docker/rust-compiler/hooks/post_push
Labels: Developer_Experience, dependencies, enhancement

#1080 docs(examples): fix supply chain image build errors
  .devcontainer/Dockerfile
  examples/cactus-example-carbon-accounting-business-logic-plugin/package.json
  examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
  examples/cactus-example-supply-chain-business-logic-plugin/package.json
  examples/supply-chain-app/.dockerignore
  examples/supply-chain-app/Dockerfile
  packages/cactus-cmd-api-server/package.json
  packages/cactus-core-api/package.json
  packages/cactus-plugin-consortium-manual/package.json
  packages/cactus-plugin-consortium-manual/src/main/json/openapi.json
  packages/cactus-plugin-htlc-eth-besu-erc20/openapitools.json
  packages/cactus-plugin-htlc-eth-besu-erc20/package.json
  packages/cactus-plugin-htlc-eth-besu/openapitools.json
  packages/cactus-plugin-htlc-eth-besu/package.json
  packages/cactus-plugin-keychain-memory/package.json
  packages/cactus-plugin-keychain-vault/package.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-corda/package.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-quorum/package.json
  packages/cactus-plugin-ledger-connector-xdai/package.json
Labels: documentation

#1061 feat(connector-besu): getTransaction method
  package-lock.json
  packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/besu-get-transaction.test.ts
Labels: Besu, enhancement

#1081 feat(connector-xdai): add interval to pollForTxReceipt
  packages/cactus-plugin-ledger-connector-xdai/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts
Labels: Xdai, bug, enhancement

#1085 feat(connector-besu): add getBalance web service
  packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-balance-endpoint.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-balance.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-balance-endpoint.test.ts
Labels: Besu, enhancement

#1033 feat(test-tooling): go-ipfs test container
  packages/cactus-test-tooling/src/main/typescript/go-ipfs/go-ipfs-test-container.ts
  packages/cactus-test-tooling/src/main/typescript/public-api.ts
Labels: Developer_Experience, enhancement

#1091 style(linter): multiple linter fix
  examples/cactus-example-supply-chain-frontend/src/app/app.component.ts
  examples/cactus-example-supply-chain-frontend/src/app/bamboo-harvest/bamboo-harvest-detail/bamboo-harvest-detail.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/bamboo-harvest/bamboo-harvest-list/bamboo-harvest-list.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/bookshelf/bookshelf-detail/bookshelf-detail.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/bookshelf/bookshelf-list/bookshelf-list.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/shipment/shipment-detail/shipment-detail.page.ts
  packages/cactus-api-client/src/main/typescript/default-consortium-provider.ts
  packages/cactus-common/src/main/typescript/logging/logger-provider.ts
  packages/cactus-common/src/test/typescript/fixtures/dummy-classes.ts
  packages/cactus-core/src/main/typescript/consortium-repository.ts
  packages/cactus-core/src/main/typescript/web-services/authorization-options-provider.ts
Labels: Developer_Experience

#1055 add node tap --ts flag to docs
  BUILD.md
  CONTRIBUTING.md
Labels: documentation
