Repository hyperledger-cacti/cacti, pull requests merged in 2021-01, with the labels that each got.

#403 feat(fabric): user defined fabric samples version
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
  packages/cactus-test-tooling/package-lock.json
  packages/cactus-test-tooling/package.json
  packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
  tools/docker/fabric-all-in-one/Dockerfile_v1.4.x
  tools/docker/fabric-all-in-one/Dockerfile_v2.x
  tools/docker/fabric-all-in-one/README.md
  tools/docker/fabric-all-in-one/healthcheck.sh
  tools/docker/fabric-all-in-one/run-fabric-network.sh
  tools/docker/fabric-all-in-one/supervisord.conf
Labels: Fabric

#409 refactor(core-api): normalize consortium data model
  examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
  packages/cactus-api-client/package.json
  packages/cactus-api-client/src/main/typescript/api-client.ts
  packages/cactus-api-client/src/main/typescript/default-consortium-provider.ts
  packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
  packages/cactus-core-api/src/main/json/generated/openapi-spec.json
  packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-core-api/src/main/typescript/openapi-spec.ts
  packages/cactus-core/src/main/typescript/consortium-repository.ts
  packages/cactus-core/src/main/typescript/index.web.ts
  packages/cactus-core/src/main/typescript/public-api.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-consortium-jws-endpoint-v1.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-node-jws-endpoint-v1.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
  packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts
  packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
  packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
  packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/security-isolation-via-api-server-ports.ts
Labels: API_Server, enhancement

#437 fix: Open API generator config - protected keyword
  package.json
  packages/cactus-core-api/package.json
  packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-core-api/src/main/typescript/openapi-spec.ts
  packages/cactus-plugin-consortium-manual/package.json
  packages/cactus-plugin-consortium-manual/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-quorum/package.json
Labels: API_Server, bug, dependencies

#435 ci(github-workflows): launch CI on PR & push for all branches
  .github/workflows/ci.yml
Labels: Developer_Experience, Hacktoberfest, enhancement, good first issue

#464 refactor: convert OpenAPI Typescript specs to JSON
  examples/cactus-example-supply-chain-backend/src/main/json/generated/openapi-spec.json
  examples/cactus-example-supply-chain-business-logic-plugin/package.json
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/json/openapi.json
  examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/openapi-spec.ts
  package.json
  packages/cactus-api-client/src/main/typescript/api-client.ts
  packages/cactus-api-client/src/main/typescript/default-consortium-provider.ts
  packages/cactus-api-client/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-api-client/src/main/typescript/generated/openapi/typescript-axios/base.ts
  packages/cactus-api-client/src/main/typescript/generated/openapi/typescript-axios/configuration.ts
  packages/cactus-api-client/src/main/typescript/generated/openapi/typescript-axios/index.ts
  packages/cactus-api-client/src/main/typescript/public-api.ts
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cmd-api-server/src/main/json/openapi.json
  packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
  packages/cactus-cmd-api-server/src/main/typescript/openapi-spec.ts
  packages/cactus-cockpit/src/app/app.component.ts
  packages/cactus-cockpit/src/app/consortium-inspector/consortium-inspector.page.ts
  packages/cactus-common/src/main/typescript/index.ts
  packages/cactus-common/src/main/typescript/nodejs/openapi-spec-json-to-fs.ts
  packages/cactus-core-api/package.json
  packages/cactus-core-api/src/main/json/openapi.json
  packages/cactus-core-api/src/main/typescript/openapi-spec.ts
  packages/cactus-core-api/src/main/typescript/public-api.ts
  packages/cactus-plugin-consortium-manual/package.json
  packages/cactus-plugin-consortium-manual/src/main/json/openapi.json
  packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-consortium-jws-endpoint-constants.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-consortium-jws-endpoint-v1.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-node-jws-endpoint-constants.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-node-jws-endpoint-v1.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/openapi-spec.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
  packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/openapi-spec.ts
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/openapi-spec.ts
  packages/cactus-plugin-ledger-connector-quorum/package.json
  packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
  packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/openapi-spec.ts
  packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
  packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/security-isolation-via-api-server-ports.ts
Labels: API_Server, Developer_Experience, SPIKE, dependencies, enhancement

#472 feat(test-tooling): containers#getById and #waitForHealthCheck
  packages/cactus-test-tooling/src/main/typescript/common/containers.ts
Labels: Developer_Experience

#470 fix(npm): clean script was missing folders
  package.json
  packages/cactus-plugin-consortium-manual/src/main/typescript/generated/openapi/typescript-axios/git_push.sh
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/git_push.sh
Labels: Hacktoberfest, bug, dependencies, good first issue

#483 build(npm): watch script
  .gitignore
  examples/cactus-example-supply-chain-backend/package.json
  examples/cactus-example-supply-chain-business-logic-plugin/package.json
  package-lock.json
  package.json
  packages/cactus-api-client/package.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-common/package.json
  packages/cactus-core-api/package.json
  packages/cactus-core/package.json
  packages/cactus-plugin-consortium-manual/package.json
  packages/cactus-plugin-keychain-memory/package.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-quorum/package.json
  packages/cactus-test-api-client/package.json
  packages/cactus-test-cmd-api-server/package.json
  packages/cactus-test-plugin-consortium-manual/package.json
  packages/cactus-test-plugin-ledger-connector-besu/package.json
  packages/cactus-test-plugin-ledger-connector-quorum/package.json
  packages/cactus-test-tooling/package.json
Labels: Developer_Experience, dependencies, enhancement

#494 fix(keychain-vault): add missing license to openapi.json
  packages/cactus-plugin-keychain-vault/src/main/json/openapi.json
Labels: bug

#488 chore: remove CircleCI configuration
  .circleci/config.yml
Labels: Developer_Experience, dependencies, documentation

#492 fix(common): servers.listen() port validation
  packages/cactus-common/src/main/typescript/servers.ts
Labels: bug

#502 fix(cockpit): compilation issues #496
  packages/cactus-api-client/src/main/typescript/default-consortium-provider.ts
  packages/cactus-api-client/src/main/typescript/generated/openapi/typescript-axios/.gitignore
  packages/cactus-api-client/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator-ignore
  packages/cactus-api-client/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/FILES
  packages/cactus-api-client/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-api-client/src/test/typescript/integration/default-consortium-provider.test.ts
  packages/cactus-cockpit/src/app/app.component.ts
  packages/cactus-cockpit/src/app/consortium-inspector/consortium-inspector.page.ts
Labels: bug

#501 fix(cmd-api-server): missing pretsc npm script #500
  packages/cactus-cmd-api-server/package-lock.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cmd-api-server/src/main/json/openapi.json
  packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator-ignore
  packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/FILES
  packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator/VERSION
  packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/base.ts
  packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/configuration.ts
  packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/index.ts
  packages/cactus-cmd-api-server/src/main/typescript/index.web.ts
  packages/cactus-cmd-api-server/src/main/typescript/public-api.ts
Labels: API_Server, bug, dependencies

#507 fix(package-json): invalid webpack commit sha #506
  package-lock.json
  package.json
Labels: bug, dependencies

#508 build(deps): upgrade axios to 0.21.1 due to high severity CVE #449
  packages/cactus-plugin-ledger-connector-besu/package-lock.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-fabric/package-lock.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-quorum/package-lock.json
  packages/cactus-plugin-ledger-connector-quorum/package.json
Labels: Security, bug, dependencies

#499 chore(deps): fabric connector upgrade bl
  packages/cactus-plugin-ledger-connector-fabric/package-lock.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
Labels: Fabric, Security, help wanted

#509 docs(reading-lists): regulatory and industry standards initiatives
  docs/regulatory-and-industry-initiatives-reading-list.md
Labels: documentation
