Repository hyperledger-cacti/cacti, pull requests merged in 2022-05, with the labels that each got.

#1973 fix(security): mitigate Cross-Site Scripting attack (XSS).
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/routes/index.ts
Labels: Security

#1590 test: jestify runtime-plugin-import test
  .taprc
  jest.config.js
  packages/cactus-test-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
Labels: Tests, Jestify

#1903 test(cmd-api-server): fix flaky runtime-plugin-imports-test
  packages/cactus-test-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
Labels: Flaky-Test-Automation, Tests

#1991 docs(maintainers): add Rama and Sandeep
  MAINTAINERS.md
Labels: documentation

#2009 test: fix jest out of memory errors on Node v16.14.2
  package.json
Labels: bug, dependencies, Developer_Experience

#1959 docs: fixed typos within whitepaper
  whitepaper/whitepaper.md
Labels: documentation

#1990 ci: bump NodeJS v14 and v16 minor versions to latest
  .devcontainer/Dockerfile
  .github/workflows/ci.yml
  BUILD.md
Labels: documentation, dependencies, Developer_Experience

#1819 fix(security): address CVE-2017-16138
  packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
  packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
  yarn.lock
Labels: dependencies, Security

#2023 docs(connector-besu): fix besu AIO image tag in README.md
  packages/cactus-plugin-ledger-connector-besu/Dockerfile
  packages/cactus-plugin-ledger-connector-besu/README.md
Labels: Besu
