Repository hyperledger-cacti/cacti, pull requests merged in 2022-03, with the labels that each got.

#1617 test: jestify transfer-complete test
  .taprc
  jest.config.js
  packages/cactus-plugin-odap-hermes/src/test/typescript/integration/odap/transfer-complete.test.ts
Labels: Tests, Jestify

#1893 docs: minor tweaks
  BUILD.md
  CONTRIBUTING.md
  tools/generate-api-server-config.js
Labels: documentation

#1879 feat(cactus-api-client): common verifier-factory
  examples/cactus-check-connection-ethereum-validator/TestEthereumVerifier.ts
  packages/cactus-api-client/src/main/typescript/public-api.ts
  packages/cactus-api-client/src/main/typescript/socketio-api-client.ts
  packages/cactus-api-client/src/main/typescript/verifier.ts
  packages/cactus-api-client/src/test/typescript/unit/socketio-api-client.test.ts
  packages/cactus-cmd-socketio-server/package.json
  packages/cactus-cmd-socketio-server/src/main/typescript/business-logic-plugin/BusinessLogicBase.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/business-logic-plugin/BusinessLogicPlugin.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/TransactionManagement.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/verifier/LedgerPlugin.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/verifier/Verifier.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/verifier/VerifierFactory.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/Verifier.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/VerifierFactory.test.ts
  packages/cactus-cmd-socketio-server/tsconfig.json
  packages/cactus-core-api/src/main/typescript/client/i-verifier.ts
  packages/cactus-core-api/src/main/typescript/plugin/ledger-connector/i-socket-api-client.ts
  packages/cactus-core-api/src/main/typescript/public-api.ts
  packages/cactus-test-api-client/package.json
  packages/cactus-test-api-client/src/test/typescript/integration/verifier-integration-with-openapi-connectors.test.ts
  packages/cactus-test-api-client/tsconfig.json
  packages/cactus-verifier-client/README.md
  packages/cactus-verifier-client/package.json
  packages/cactus-verifier-client/src/main/typescript/get-validator-api-client.ts
  packages/cactus-verifier-client/src/main/typescript/index.ts
  packages/cactus-verifier-client/src/main/typescript/public-api.ts
  packages/cactus-verifier-client/src/main/typescript/verifier-factory.ts
  packages/cactus-verifier-client/src/main/typescript/verifier.ts
  packages/cactus-verifier-client/src/test/typescript/unit/get-validator-api-client.test.ts
  packages/cactus-verifier-client/src/test/typescript/unit/verifier-factory.test.ts
  packages/cactus-verifier-client/src/test/typescript/unit/verifier.test.ts
  packages/cactus-verifier-client/tsconfig.json
  tsconfig.json
Labels: Besu

#1880 docs(faq): add instructions to install in Apple M1 processor (ARM-based)
  FAQ.md
Labels: documentation, Developer_Experience

#1683 ci: ensure sorted json files
  .github/workflows/ci.yml
  examples/cactus-example-carbon-accounting-backend/package.json
  examples/cactus-example-carbon-accounting-business-logic-plugin/package.json
  examples/cactus-example-carbon-accounting-frontend/package.json
  examples/cactus-example-supply-chain-backend/package.json
  examples/cactus-example-supply-chain-business-logic-plugin/package.json
  examples/cactus-example-supply-chain-frontend/package.json
  extensions/cactus-plugin-htlc-coordinator-besu/package.json
  extensions/cactus-plugin-object-store-ipfs/package.json
  extensions/cactus-plugin-object-store-ipfs/src/test/typescript/fixtures/mock/ipfs/ipfs-files-api-mock.ts
  package.json
  packages/cactus-api-client/package.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-common/package.json
  packages/cactus-core-api/package.json
  packages/cactus-core/package.json
  packages/cactus-plugin-consortium-manual/package.json
  packages/cactus-plugin-htlc-eth-besu-erc20/package.json
  packages/cactus-plugin-htlc-eth-besu/package.json
  packages/cactus-plugin-keychain-aws-sm/package.json
  packages/cactus-plugin-keychain-azure-kv/package.json
  packages/cactus-plugin-keychain-google-sm/package.json
  packages/cactus-plugin-keychain-memory-wasm/package.json
  packages/cactus-plugin-keychain-memory/package.json
  packages/cactus-plugin-keychain-vault/package.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-corda/package.json
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-iroha/package.json
  packages/cactus-plugin-ledger-connector-quorum/package.json
  packages/cactus-plugin-ledger-connector-xdai/package.json
  packages/cactus-plugin-odap-hermes/package.json
  packages/cactus-test-api-client/package.json
  packages/cactus-test-cmd-api-server/package.json
  packages/cactus-test-plugin-consortium-manual/package.json
  packages/cactus-test-plugin-htlc-eth-besu-erc20/package.json
  packages/cactus-test-plugin-htlc-eth-besu/package.json
  packages/cactus-test-plugin-ledger-connector-besu/package.json
  packages/cactus-test-plugin-ledger-connector-quorum/package.json
  packages/cactus-test-tooling/package.json
  tools/custom-checks/check-package-json-sort.ts
  tools/custom-checks/run-custom-checks.ts
  yarn.lock
Labels: enhancement, Developer_Experience

#1910 fix(connector-fabric): uncontrolled data used in path expression
  packages/cactus-plugin-ledger-connector-fabric/package.json
  packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-source/deploy-contract-go-source-endpoint-v1.ts
  yarn.lock
Labels: dependencies, Security, P1

#1908 fix(cmd-api-server): add express static rate limiting
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
  yarn.lock
Labels: API_Server, Security, P1

#1913 fix(security): address CVE-2021-23358 - TEMPORARY fix
  package.json
Labels: Besu, dependencies, Security, P1

#1839 ci: fix CodeQL security scans
  .github/workflows/codeql-analysis.yml
Labels: dependencies, Security, Developer_Experience, P1

#1915 fix(cmd-api-server): upgrade socket.io - CVE-2022-21676
  examples/cactus-check-connection-ethereum-validator/package.json
  examples/discounted-cartrade/package.json
  examples/electricity-trade/package.json
  examples/electricity-trade/tools/transferNumericAsset/package.json
  examples/test-run-transaction/package.json
  extensions/cactus-plugin-htlc-coordinator-besu/package.json
  packages/cactus-cmd-api-server/package.json
  packages/cactus-cmd-api-server/src/main/typescript/api-client/api-server-api-client.ts
  packages/cactus-cmd-socketio-server/package.json
  packages/cactus-core-api/package.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
  packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
  packages/cactus-plugin-odap-hermes/package.json
  yarn.lock
Labels: API_Server, dependencies, Security, P1

#1917 fix(deps): ensure glob-parent is above 5.1.2 - CVE-2020-28469
  package.json
  packages/cactus-plugin-keychain-memory-wasm/package.json
  yarn.lock
Labels: dependencies, Security, P1

#1921 fix(security): ensure ansi-html > 0.0.8 - CVE-2021-23424
  package.json
  yarn.lock
Labels: dependencies, Security, P1

#1919 fix(security): force lodash > 4.17.20 - CVE-2020-8203
  package.json
  yarn.lock
Labels: dependencies, Security, P1

#1930 ci: add fuzzer tests for our APIs
  .github/workflows/.dast-nuclei-cmd-api-server.yaml
  .nuclei-config.yaml
Labels: API_Server, Security, P1

#1934 docs(plugin-object-store-ipfs): added README.md description
  extensions/cactus-plugin-object-store-ipfs/README.md
Labels: documentation

#1944 fix(deps): force minimist >=1.2.6 for CVE-2021-44906
  package.json
Labels: dependencies, Security, P1

#1948 fix(security): ensure node-forge > 1.3.0 for CVE-2022-24772
  package.json
  packages/cactus-cmd-api-server/package.json
  yarn.lock
Labels: dependencies, Security, P1

#873 docs(htlc-coordinator): added the flow diagram
  docs/htlc-coordinator-alice-flow.md
  docs/htlc-coordinator-bob-flow.md
Labels: documentation

#1816 fix(security): address CVE-2021-23358
  packages/cactus-plugin-htlc-eth-besu/package.json
  packages/cactus-plugin-ledger-connector-besu/package.json
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-cactus.test.ts
  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-web3-eea.test.ts
  packages/cactus-test-plugin-htlc-eth-besu/package.json
  packages/cactus-test-plugin-ledger-connector-besu/package.json
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-balance-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-past-logs-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-transaction-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/sign-transaction-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-get-balance-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-get-past-logs-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-get-transaction-endpoint.test.ts
  packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-sign-transaction-endpoint.test.ts
  typings/web3js-quorum/index.d.ts
Labels: enhancement, Quorum, Besu, dependencies, Security, P1

#1953 ci(tools): fix iroha AIO image build flake on CI
  tools/docker/iroha-all-in-one/Dockerfile
Labels: dependencies, Tests
