Repository hyperledger-cacti/cacti, pull requests merged in 2022-04, with the labels that each got.

#1955 docs: fix diagram typo in connector README files
  packages/cactus-plugin-ledger-connector-besu/README.md
  packages/cactus-plugin-ledger-connector-fabric/README.md
  packages/cactus-plugin-ledger-connector-xdai/README.md
Labels: documentation

#1206 feat(keychain-azure-kv): complete request handler and endpoints #1010
  packages/cactus-plugin-keychain-azure-kv/package.json
  packages/cactus-plugin-keychain-azure-kv/src/main/json/openapi.json
  packages/cactus-plugin-keychain-azure-kv/src/main/typescript/generated/openapi/typescript-axios/api.ts
  packages/cactus-plugin-keychain-azure-kv/src/main/typescript/plugin-factory-keychain.ts
  packages/cactus-plugin-keychain-azure-kv/src/main/typescript/plugin-keychain-azure-kv.ts
  packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/delete-keychain-entry-endpoint.ts
  packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/get-keychain-entry-endpoint.ts
  packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/has-keychain-entry-endpoint.ts
  packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/set-keychain-entry-endpoint.ts
  packages/cactus-plugin-keychain-azure-kv/src/test/typescript/integration/plugin-keychain-azure-kv.test.ts
Labels: enhancement, Keychain

#1801 feat: add jwt authorization to supply chain example
  README.md
  examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
  examples/cactus-example-supply-chain-frontend/src/app/app.module.ts
  examples/cactus-example-supply-chain-frontend/src/app/bamboo-harvest/bamboo-harvest-list/bamboo-harvest-list.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/bookshelf/bookshelf-detail/bookshelf-detail.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/bookshelf/bookshelf-list/bookshelf-list.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/common/auth-config.ts
  examples/cactus-example-supply-chain-frontend/src/app/shipment/shipment-detail/shipment-detail.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/shipment/shipment-list/shipment-list.page.ts
  examples/supply-chain-app/README.md
Labels: documentation, API_Server, Security

#1901 docs(whitepaper): update abstract, introduction, interop. model
  whitepaper/whitepaper.md
Labels: documentation, enhancement, Developer_Experience

#1928 refactor(quorum-multi-party-all-in-one): enhance quorum-mp image
  .cspell.json
  .github/workflows/ci.yml
  .github/workflows/quorum-multi-party-all-in-one-publish.yaml
  packages/cactus-test-tooling/src/main/typescript/common/containers.ts
  packages/cactus-test-tooling/src/main/typescript/public-api.ts
  packages/cactus-test-tooling/src/main/typescript/quorum/quorum-mp-test-ledger.ts
  tools/docker/quorum-multi-party-all-in-one/Dockerfile
  tools/docker/quorum-multi-party-all-in-one/README.md
  tools/docker/quorum-multi-party-all-in-one/healthcheck.sh
  tools/docker/quorum-multi-party-all-in-one/supervisord.conf
Labels: Tests

#1960 docs: add descriptions of ledgers in whitepaper
  whitepaper/whitepaper.md
Labels: documentation

#1810 docs: add link and image of jdk 8 install to build.md
  BUILD.md
Labels: documentation, Developer_Experience

#1970 docs(readme): add missing inclusive language statement
  README.md
Labels: documentation, Developer_Experience

#1958 ci(connector-fabric): include endpoints in the fuzzer tests
  .github/workflows/.dast-nuclei-cmd-api-server.yaml
  packages/cactus-plugin-ledger-connector-fabric/README.md
Labels: Fabric, Security

#1986 docs(readme): replaced rocketchat link with discord link in README
  README.md
Labels: documentation
