Repository hyperledger-cacti/cacti, pull requests merged in 2022-02, with the labels that each got.

#1807 test(api-client): fix flaky socketio-api-client.test
  packages/cactus-api-client/src/test/typescript/unit/socketio-api-client.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/Verifier.test.ts
Labels: Flaky-Test-Automation, Tests

#1686 test: jestify js-object-signer test
  .taprc
  jest.config.js
  packages/cactus-common/src/test/typescript/unit/js-object-signer.test.ts
Labels: Tests, Jestify

#1793 style: 2021-09-20 linter warnings batch 20 / 26 #1369
  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/openapi/openapi-validation.test.ts
Labels: Developer_Experience

#1826 build(examples): bump log4js from 3.0.6 to 6.4.0
  contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/cooperation/coreSide/ec1_adapter/package.json
  contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/cooperation/coreSide/ec2_adapter/package.json
  contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/cooperation/ecSide/ec1_connector/package.json
  contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/cooperation/ecSide/ec2_connector/package.json
  contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/restserver/coreapi/package.json
  examples/cartrade/package.json
  examples/cartrade/validatorDriver/package.json
  examples/discounted-cartrade/package.json
  examples/discounted-cartrade/validatorDriver/package.json
  examples/electricity-trade/package.json
  examples/test-run-transaction/package.json
Labels: dependencies, Security

#1800 fix(plugin-ledger-connector-fabric-socketio): upgrade Fabric due to jsrsasign
  examples/cartrade/package.json
  examples/discounted-cartrade/package.json
  packages/cactus-cmd-socketio-server/package.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
  yarn.lock
Labels: bug, Fabric, Security

#1828 test(api-client): fix flaky verifier-integration-with-openapi-connectors
  packages/cactus-api-client/src/test/typescript/unit/verifier.test.ts
  packages/cactus-test-api-client/src/test/typescript/integration/verifier-integration-with-openapi-connectors.test.ts
Labels: Flaky-Test-Automation, Tests

#1821 docs: changes to BUILD.md and CONTRIBUTING.md #1792
  BUILD.md
  CONTRIBUTING.md
Labels: documentation

#1822 style: 2021-09-20 linter warnings batch 24 / 26
  packages/cactus-test-tooling/src/main/typescript/postgres/postgres-test-container.ts
Labels: Tests

#1834 test(common): fix assertion of signature equality
  packages/cactus-common/src/test/typescript/unit/js-object-signer.test.ts
Labels: bug, Tests

#1846 style(test-tooling): fix unexpected any quorum test ledger destroy
  packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
Labels: Developer_Experience

#1847 style(test-tooling): fix unexpected any quorum test ledger start
  packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
Labels: enhancement, Developer_Experience

#1629 test: ethereum BLP with connectivity check
  examples/cactus-check-connection-ethereum-validator/BusinessLogicCheckEthereumValidator.ts
  examples/cactus-check-connection-ethereum-validator/README.MD
  examples/cactus-check-connection-ethereum-validator/RequestInfo.ts
  examples/cactus-check-connection-ethereum-validator/TestEthereumBalance.ts
  examples/cactus-check-connection-ethereum-validator/check-ethereum-validator.ts
  examples/cactus-check-connection-ethereum-validator/config/BLP_config.ts
  examples/cactus-check-connection-ethereum-validator/config/default.yaml
  examples/cactus-check-connection-ethereum-validator/config/usersetting.yaml
  examples/cactus-check-connection-ethereum-validator/copyBLPConfig.ts
  examples/cactus-check-connection-ethereum-validator/copyStaticAssets.ts
  examples/cactus-check-connection-ethereum-validator/package.json
  examples/cactus-check-connection-ethereum-validator/replaceBLPConfigPath.ts
  examples/cactus-check-connection-ethereum-validator/src/test/typescript/integration/check-connection-to-ledger.test.ts
  examples/cactus-check-connection-ethereum-validator/tsconfig.json
  jest.config.js
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/TransactionManagement.ts
Labels: Tests

#1867 refactor(cmd-socketio): fix strict flag warnings
  examples/discounted-cartrade/trades.ts
  examples/electricity-trade/electricity-trade.ts
  examples/test-run-transaction/test-run-transaction.ts
  packages/cactus-cmd-socketio-server/package.json
  packages/cactus-cmd-socketio-server/src/main/typescript/business-logic-plugin/BusinessLogicBase.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/CactusSocketIOServer.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/RequestInfo.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/TransactionManagement.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/routes/login.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/util/RIFUtil.test.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/util/TransactionSigner.ts
  packages/cactus-cmd-socketio-server/tsconfig.json
  yarn.lock
Labels: Developer_Experience

#1796 fix(security): address CVE-2019-5413
  packages/cactus-cmd-socketio-server/package.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
  packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
  yarn.lock
Labels: dependencies, Security
