Repository hyperledger-cacti/cacti, pull requests merged in 2022-01, with the labels that each got.

#1660 feat(cactus-api-client): add support for plain socketio validators in api-server and api-client
  packages/cactus-api-client/package.json
  packages/cactus-api-client/src/main/typescript/index.web.ts
  packages/cactus-api-client/src/main/typescript/public-api.ts
  packages/cactus-api-client/src/main/typescript/socketio-api-client.ts
  packages/cactus-api-client/src/main/typescript/verifier.ts
  packages/cactus-api-client/src/test/typescript/unit/socketio-api-client.test.ts
  packages/cactus-api-client/src/test/typescript/unit/verifier.test.ts
  packages/cactus-api-client/tsconfig.json
  packages/cactus-core-api/package.json
  packages/cactus-core-api/src/main/typescript/plugin/ledger-connector/i-socket-api-client.ts
  packages/cactus-core-api/src/main/typescript/public-api.ts
  packages/cactus-plugin-ledger-connector-besu/src/main/typescript/api-client/besu-api-client.ts
  packages/cactus-test-api-client/src/test/typescript/integration/verifier-integration-with-openapi-connectors.test.ts
  packages/cactus-test-tooling/src/main/typescript/public-api.ts
  packages/cactus-test-tooling/src/main/typescript/socketio-test-setup-helpers/socketio-test-setup-helpers.ts
Labels: enhancement, API_Server, ConnectionChain

#1670 build: include cmd-socketio-server and socketio validators in the monorepo setup
  examples/cartrade/README.md
  examples/cartrade/package.json
  examples/electricity-trade/README.md
  examples/electricity-trade/cleanup.sh
  examples/electricity-trade/package.json
  package.json
  packages/cactus-cmd-socketio-server/package.json
  packages/cactus-cmd-socketio-server/src/main/typescript/verifier/Verifier.ts
  packages/cactus-cmd-socketio-server/tsconfig.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/README.md
  packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/tsconfig.json
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/Dockerfile
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/README.md
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/tsconfig.json
  packages/cactus-plugin-ledger-connector-sawtooth-socketio/Dockerfile
  packages/cactus-plugin-ledger-connector-sawtooth-socketio/README.md
  packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
  packages/cactus-plugin-ledger-connector-sawtooth-socketio/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: Developer_Experience

#1689 test: jestify get-single-status-endpoint-invalid test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint-invalid.test.ts
Labels: Tests, Jestify

#1688 test: jestify new-contract-endpoint-invalid test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts
Labels: Tests, Jestify

#1696 build(socket.io, socket.io-client): upgrade to common socket.io version
  examples/cartrade/package.json
  examples/cartrade/script-test-getFunctions/fabric/package.json
  examples/cartrade/validatorDriver/package.json
  examples/discounted-cartrade/package.json
  examples/discounted-cartrade/script-test-getFunctions/fabric/package.json
  examples/discounted-cartrade/validatorDriver/package.json
  examples/discounted-cartrade/validatorDriver/src/driver-common.ts
  examples/discounted-cartrade/validatorDriver/src/ethereumValidatorAccess.ts
  examples/discounted-cartrade/validatorDriver/src/fabricValidatorAccess.ts
  examples/discounted-cartrade/validatorDriver/testDriver_sendSignedProposal.js
  examples/electricity-trade/package.json
  examples/electricity-trade/tools/transferNumericAsset/package.json
  examples/electricity-trade/tools/transferNumericAsset/transferNumericAsset.ts
  examples/test-run-transaction/package.json
  jest.config.js
  packages-python/cactus_validator_socketio/testcli/package.json
  packages-python/cactus_validator_socketio_iroha/README.md
  packages-python/cactus_validator_socketio_iroha/testcli/package.json
  packages/cactus-cmd-socketio-server/jest.config.js
  packages/cactus-cmd-socketio-server/package.json
  packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/util/DBAccess.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/verifier/Verifier.ts
  packages/cactus-cmd-socketio-server/src/main/typescript/verifier/validator-registry.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/DriverCommon.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/TestSocketHelpers.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/ValidatorAuthentication.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/Verifier.test.ts
  packages/cactus-cmd-socketio-server/src/test/typescript/unit/VerifierFactory.test.ts
  packages/cactus-cmd-socketio-server/tsconfig.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/common/core/bin/www.ts
  packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/unit-test/package.json
  packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/unit-test/validatorDriver_changeCarOwner.ts
  packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/unit-test/validatorDriver_queryAllCars.ts
  packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/unit-test/validatorDriver_queryCar.ts
  packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/unit-test/validatorDriver_signTransactionOffline.ts
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/common/core/bin/www.ts
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/unit-test/package.json
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/unit-test/validatorDriver_getNonceHex.ts
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/unit-test/validatorDriver_getNumericBalance.ts
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/unit-test/validatorDriver_sendRawTransaction.ts
  packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/unit-test/validatorDriver_transferNumericAsset.ts
  packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
  packages/cactus-plugin-ledger-connector-sawtooth-socketio/src/main/typescript/common/core/bin/www.ts
  tools/docker/indy-testnet/README.md
  tools/docker/indy-testnet/docker-compose.yaml
  tools/docker/indy-testnet/validator/requirements.txt
Labels: dependencies

#1763 build(dev-container): add Rust toolchain (cargo, rustc, etc.)
  .devcontainer/Dockerfile
Labels: enhancement, dependencies, Developer_Experience, P2, Weaver

#1692 test: jestify get-status-endpoint-invalid test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint-invalid.test.ts
Labels: Tests, Jestify

#1700 test: jestify get-single-status-endpoint test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts
Labels: Besu, Tests, Jestify

#1699 test: jestify refund-endpoint test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint.test.ts
Labels: Besu, Tests, Jestify

#1676 fix: add optional auth token to api-client and consortium-manual
  examples/cactus-example-supply-chain-frontend/src/app/bamboo-harvest/bamboo-harvest-list/bamboo-harvest-list.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/bookshelf/bookshelf-detail/bookshelf-detail.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/bookshelf/bookshelf-list/bookshelf-list.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/shipment/shipment-detail/shipment-detail.page.ts
  examples/cactus-example-supply-chain-frontend/src/app/shipment/shipment-list/shipment-list.page.ts
  packages/cactus-api-client/src/main/typescript/api-client.ts
  packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
  packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
Labels: bug

#1701 test(test-tooling): add corda 5 aio image #1479
  tools/docker/corda-all-in-one/README.md
  tools/docker/corda-all-in-one/corda-v5/Dockerfile
  tools/docker/corda-all-in-one/corda-v5/healthcheck.sh
  tools/docker/corda-all-in-one/corda-v5/start-services.sh
  tools/docker/corda-all-in-one/corda-v5/supervisor/corda5-solarsystem-contracts-demo-network.conf
Labels: Corda, Tests

#1761 feat(connector-corda): read privateKey from filesystem
  packages/cactus-plugin-ledger-connector-corda/src/main/typescript/plugin-ledger-connector-corda.ts
Labels: enhancement, Corda

#1691 test: jestify test-plugin-htlc-eth-besu get-status-endpoint test
  .taprc
  jest.config.js
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint.test.ts
Labels: Tests, Jestify

#1794 docs(cactus-core-api): add README file
  packages/cactus-core-api/README.md
Labels: documentation, Developer_Experience, Core_API

#1708 test(test-plugin-htlc-eth-besu): fix neg test case
  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint-invalid.test.ts
Labels: Besu, Developer_Experience, Tests

#1790 ci: fix Could not get resource https://jcenter.bintray.com/
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/.idea/jarRepositories.xml
  packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/build.gradle.kts
  tools/docker/corda-all-in-one/corda-v4_8-flowdb/build.gradle
Labels: bug, Corda, dependencies

#1765 style: 2021-09-20 linter warnings batch 23/26
  packages/cactus-test-tooling/src/main/typescript/http-echo/http-echo-container.ts
Labels: Developer_Experience, Tests

#1595 test: jestify plugin-registry test
  .taprc
  jest.config.js
  packages/cactus-core/src/test/typescript/unit/plugin-registry.test.ts
Labels: Tests, Jestify

#1680 test: jestify jwt-endpoint-authorization test
  .taprc
  jest.config.js
  packages/cactus-cmd-api-server/src/test/typescript/integration/jwt-endpoint-authorization.test.ts
Labels: Tests, Jestify

#1767 style: 2021-09-20 linter warnings batch 19 / 26
  packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/openapi/openapi-validation.test.ts
  packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts
  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/openapi/openapi-validation.test.ts
Labels: Developer_Experience, Xdai, Tests

#1764 style: 2021-09-20 linter warnings batch 21/26
  packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/openapi/openapi-validation.test.ts
Labels: Developer_Experience
